name: SharpCompress
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          6.0.x
    - run: dotnet run -p build/build.csproj
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-sharpcompress.nupkg
        path: artifacts/*
